name: Build and Deploy a python app
on:
    push:
        branches:
        - main
jobs:
    build:
        name: Build python app
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
            - name: Install librairies
              run: |
                    cd function
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
            - name: Create zip bundle
              run: |
                    cd function
                    zip -r ../${{ github.sha }}.zip .
            - name: Archive artifact
              uses: actions/upload-artifact@v4
              with:
                name: Zupped bundle
                path: ${{ github.sha }}.zip
    publish:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
          - name: Create Release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
            with:
              tag_name: ${{ github.run_number }}
              release_name: Release ${{ github.run_number }}
              body: |
                New Release for ${{ github.sha }}
                - First Change
                - Second Change
              draft: false
              prerelease: false
  
