name: Build and Deploy a python app
on:
    push:
        branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
            - name: Install librairies
              run: |
                    cd function
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
            - name: Create zip bundle
              run: |
                    cd function
                    zip -r ../${{ github.sha }}.zip .
            - name: Archive artifact
              uses: actions/upload-artifact@v4
              with:
                name: Zupped bundle
                path: ${{ github.sha }}.zip
  
